### ISSUE TITLE
wavefront_alert configuration errors not caught by `terraform validate` nor `terraform plan`

### ISSUE THREAD

**Issue by ctodd-cb** [vmware/terraform-provider-wavefront#39]
I misconfigured a `wavefront_alert` by failing to match the `display_expression` value to the `conditions` content. I ran `terraform validate` and the module validated successfully. I repeated on my instantiation module with the same response. I received a valid plan. However, only after `terraform apply` failed did I receive feedback that my resource was improperly defined. 

I've generalized the resource names below.

```
module.wavefront_alert_dev.wavefront_alert.my_s3_bucket: Creating...
Error: error creating Alert Dev My Bucket Updated. server returned 400 Bad Request
{"status":{"result":"ERROR","message":"condition does not match display expression.","code":400}}
```

I'm unsure if this is a feature request or a bug.

**Comment by keep94** [comment]
Thank you for opening this issue.

https://www.terraform.io/docs/commands/validate.html says that `terraform validate` validates the configuration files without using any provider APIs.  However, when you run `terraform apply` it does use provider APIs. The error message that you see when you run `terraform plan` is coming from the provider API.  `terraform validate` cannot catch this error as it doesn't use the provider API.

This issue would be a feature request.  I don't yet know whether or not terraform can be programmed to do this type of validation ahead of time.

**Comment by ctodd-cb** [comment]
Thanks for the explanation. I can't really speak to the technical implementation here, just the user experience. 

We mainly use TF for AWS and SignalFx and use pull requests for our peer review / TF Apply. So, waiting until the apply to identify configuration issues and then guessing at the misconfiguration feels more like cURL and less like Terraform. I ended up forgoing our CD tool and iterating locally out of frustration and we just don't want that experience for our contributors.

**Comment by keep94** [comment]
Closing this issue for now.
