### ISSUE TITLE
Support for logarithmic charts

### ISSUE THREAD

**Issue by m104** [vmware/terraform-provider-wavefront#48]
Hello Wavefront support,

I don't see a way to support logarithmic charts currently (`base` value other than `0`), besides importing a JSON blob for the entire dashboard. It looks like we'd just need to support the `base` value in the [chart schema definition](https://github.com/vmware/terraform-provider-wavefront/blob/818e213b157a408f043868944261b52b1d5ef6b4/wavefront/resource_dashboard.go#L361).

Thanks in advance!

**Comment by keep94** [comment]
The base value in the chart schema definition is now supported in v2.7.3.
