### ISSUE TITLE
Wavefront terraform provider fails to find existing external IDs for AWS integration

### ISSUE THREAD

**Issue by sampointer** [vmware/terraform-provider-wavefront#61]
[headers.txt](https://github.com/vmware/terraform-provider-wavefront/files/5945437/headers.txt)
We maintain 50 instances of the AWS Cloud Integrations (and intend to add more as we onboard more accounts) split evenly between the Cloudwatch and EC2 variants using the Terraform provider.

More often than not a re-assertion of the state throws a 404 when attempting to fetch the external id stored in the Terraform state.

Specifically, this 404 is thrown from https://github.com/vmware/terraform-provider-wavefront/blob/master/wavefront/resource_cloud_integration_aws_external_id.go#L39

Capturing the headers (attached) we can see that, after the integration is configured and the external ID is stored in the state the verification fails as the backend legitimately returns a 404.

We also see the following on many occasions, although I do not think it is the root cause:
```
Error: error creating Cloud Integration for service CLOUDWATCH. got server returned 400 Bad Request
112 | {"status":{"result":"ERROR","message":"Errors while saving credential with id null :Trying to use invalid AWS External ID.  You must use an external ID generated by Wavefront.","code":400}}
113 |  
114 |  
115 | on ../../../modules/terraform-aws-wavefront-cloud-integration/main.tf line 46, in resource "wavefront_cloud_integration_cloudwatch" "cloudwatch":
116 | 46: resource "wavefront_cloud_integration_cloudwatch" "cloudwatch" {
117 |  
118 |  
119 |  
120 | Error: error creating Cloud Integration for service EC2. got server returned 406 Not Acceptable
121 | {"status":{"result":"ERROR","message":"Cannot update cloud integration - rate limit exceeded.","code":406}}
122 |  
123 |  
124 | on ../../../modules/terraform-aws-wavefront-cloud-integration/main.tf line 56, in resource "wavefront_cloud_integration_ec2" "ec2":
125 | 56: resource "wavefront_cloud_integration_ec2" "ec2" {
126
```

We suspect there is some issue with the persistence of external IDs.

In many cases the only effect of this is that the integration is re-created. However, in many cases we see that process also fail as the provider attempts to use an external ID of "null".

It is of note that we assert the state of these 50 integrations (by running Terraform) tens of times a day. Because of the above failure mode we therefore re-create them more often than not 10 of times a day each. Many of these assertions happen approximately concurrently.

This relates to ZenDesk issue `15671`.

**Comment by keep94** [comment]
The terraform plugin uses the go wavefront API to do its work.  I wrote a small go program using the go wavefront API to create and verify an AWS external ID.  That part of it seems to be working, so as you suggested earlier, perhaps terraform is somehow loosing the external ID?

I would like to reproduce this problem with a small and simple terraform file.  How are you using AWS external IDs? Is it possible for you to furnish a sample main.tf file that exposes this bug?

**Comment by sampointer** [comment]
Our setup is pretty involved. I've attached the module that is run against the 25 or so accounts and also included within that tarball the tests we run against the module to ensure it is functioning correctly independently. Some of the dependencies that enable the latter to work are missing and sharing them is non-trivial, but it'll give you an idea of what we're asserting on.

Those unit test asserts pass consistently. You'll note that there is an assertion that re-applies the integration 10 times in place 
[wavefront_module.zip](https://github.com/vmware/terraform-provider-wavefront/files/5967083/wavefront_module.zip)

to address the concern you raise of Terraform "losing" the external_id from the state file.

If you look at the dump of headers I included on the Zen Desk issue you'll note that the external ID is correctly retrieved from the state but is not returned by the backend when the `cloudIntegrations.VerifyAwsExternalID()` function is called.

Between the included unit tests and the headers on that internal issue tracker I'm pretty sure the error is one of volume or concurrency on the back-end. We hit the API for external ID 50 or so times concurrently.

**Comment by keep94** [comment]
I unzipped the file you attached above, and the wavefront_module folder within appears to be empty. Also the zip file is quite small, only 184 bytes. Can you double check that the content is included in the zip file?

**Comment by sampointer** [comment]
My mistake! Please find a file with contents attached :)
[wavefront_module.zip](https://github.com/vmware/terraform-provider-wavefront/files/5971498/wavefront_module.zip)

**Comment by keep94** [comment]
Thank you for your patience sam. I spent some time yesterday looking through your tests.  My first goal is to run your tests and maybe reproduce the error. Inside the zip file, I see several terraform files in addition to main.tf.  I've only used main.tf, so I would like to understand what the other tf files are for.  I also see a go program that looks like it runs terraform tests programatically.  I am wondering how to link the .tf files to the go program.  Is the go program required to run the tests? or can the tests be run using a simple terraform command?  When the aws external ID is lost or forgotten, do these automated tests fail?

**Comment by sampointer** [comment]
Terraform does not care what the `.tf` files are called: it compiles them all into one AST to execute. The resources are split out for clarity and maintenance only. From my prior comment:

> The Go files with the tests are there for information only. They do not reproduce the error. This is the crucial point. From my previous comment:

> Our setup is pretty involved. I've attached the module that is run against the 25 or so accounts and also included within that tarball the tests we run against the module to ensure it is functioning correctly independently. Some of the dependencies that enable the latter to work are missing and sharing them is non-trivial, but it'll give you an idea of what we're asserting on. I could probably share them via a non-public forum. However, since they don't reproduce the problem there's probably not much value in that.

> Those unit test assertions pass consistently. You'll note that there is an assertion that re-applies the integration 10 times in place to address the concern you raise of Terraform "losing" the external_id from the state file. These tests get run about 1,800 times a month and so we're fairly confident they are robust.

and

> To be perfectly clear: in order to reproduce this you'll have to hit the API with a degree of concurrency: a single independent test case will not.


To reiterate: the tests are included by way of proof that we assert that this module behaves correctly when executed in isolation. The problem at hand is that when one runs tens of instances of this module concurrently against the API the `externalId` fails in the manner described by the headers included in the ZenDesk ticket.

**Comment by sampointer** [comment]
Back-end changes made by Wavefront have fixed this issue.
