### ISSUE TITLE
Support for Metrics Policy & Various Data Sources

### ISSUE THREAD

**Issue by ssnorrizaurous** [vmware/terraform-provider-wavefront#82]
### Is your feature request related to a problem? Please describe.

Woven Planet is building a Centralized Observability Platform which requires programmatically scoping metrics by namespaces / groups. We need to be able to update our metrics policy based on new scoped groups / namespaces from our consumers as well as have other teams inspect the current state of wavefront resources. I will be raising a PR to address this ask.

### Describe the solution you'd like

We wish to have access to a 'wavefront_metrics_policy' resource to accomplish this. Additionally we would like Data Sources for Users, Groups, Roles, and Metrics Policy to facilitate customers understanding the state of our central platform in separate terraform projects.

**Comment by ssnorrizaurous** [comment]
Associated api changes issue is [here](https://github.com/wavefrontHQ/go-wavefront-management-api/issues/45).

**Comment by bwinter** [comment]
@ssnorrizaurous - it looks like this work was completed and merged; so, I am going to close this Issue. If that's wrong we can reopen it. Thanks!
